/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bethaa
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulir = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        Alamat1 = new javax.swing.JLabel();
        alamat1 = new javax.swing.JTextField();
        Kelas1 = new javax.swing.JLabel();
        kelas1 = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        Nama = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        Kelas = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        Alamat = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        formulir.setText("FORMULIR PENDAFTARAN ");
        getContentPane().add(formulir);
        formulir.setBounds(130, 20, 190, 30);

        Nama1.setText("Nama :");
        getContentPane().add(Nama1);
        Nama1.setBounds(50, 280, 50, 30);
        getContentPane().add(nama1);
        nama1.setBounds(100, 280, 230, 30);

        Alamat1.setText("Alamat :");
        getContentPane().add(Alamat1);
        Alamat1.setBounds(50, 380, 50, 30);
        getContentPane().add(alamat1);
        alamat1.setBounds(100, 380, 230, 30);

        Kelas1.setText("Kelas :");
        getContentPane().add(Kelas1);
        Kelas1.setBounds(50, 330, 50, 30);
        getContentPane().add(kelas1);
        kelas1.setBounds(100, 330, 230, 30);

        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(150, 240, 100, 23);

        Nama.setText("Nama :");
        getContentPane().add(Nama);
        Nama.setBounds(50, 80, 50, 30);
        getContentPane().add(nama);
        nama.setBounds(100, 80, 230, 30);

        Kelas.setText("Kelas :");
        getContentPane().add(Kelas);
        Kelas.setBounds(50, 130, 50, 30);
        getContentPane().add(kelas);
        kelas.setBounds(100, 130, 230, 30);

        Alamat.setText("Alamat :");
        getContentPane().add(Alamat);
        Alamat.setBounds(50, 180, 50, 30);
        getContentPane().add(alamat);
        alamat.setBounds(100, 180, 230, 30);

        setSize(new java.awt.Dimension(416, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        
        String Nama = nama.getText();
        nama1.setText(Nama);
        String Kelas =kelas.getText();
        kelas1.setText(Kelas);
        String Alamat = alamat.getText();
        alamat1.setText(Alamat);
        
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Alamat1;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Kelas1;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField alamat1;
    private javax.swing.JLabel formulir;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField kelas1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
